name: Update Installer Config

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  update-config:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Lua
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.3

      - name: Generate Config
        run: |
          lua tools/generate-config.lua
          
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add config.lua
          git commit -m "Update installer config" || exit 0
          git push