name: Update Installer Config

on:
    push:
        branches:
        - main
        paths:
        - 'src/**'

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate Config
        run: |
          lua scripts/generate-config.lua