name: Minify Lua Code

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  minify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Lua minifier
      run: |
        npm install luamin
        echo "Testing luamin installation:"
        npx luamin --version || echo "luamin version check failed"

    - name: Combine and Minify Lua files
      run: |
        mkdir -p release
        
        echo "Testing main.lua minification only..."
        if npx luamin -f src/main.lua > release/main.min.lua; then
          echo "Main.lua minification successful"
        else
          echo "Lua syntax check failed. Trying to identify the error:"
          # Versuche den Lua-Code zu parsen um Syntax-Fehler zu finden
          luac -p src/main.lua || echo "Lua syntax error detected"
          exit 1
        fi

    - name: Commit minified Lua file
      if: success()
      run: |
        if [ -s release/main.min.lua ]; then
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add release/main.min.lua
          git commit -m 'Minify main.lua'
          git push
        else
          echo "Error: main.min.lua is empty or doesn't exist"
          exit 1
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
